In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("manishkr1754/cardekho-used-car-data")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/manishkr1754/cardekho-used-car-data?dataset_version_number=2...

100%|██████████| 230k/230k [00:00<00:00, 52.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/manishkr1754/cardekho-used-car-data/versions/2

In [ ]:
df=pd.read_csv('/root/.cache/kagglehub/datasets/manishkr1754/cardekho-used-car-data/versions/2/cardekho_dataset.csv')

In [ ]:
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [ ]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15411 non-null  int64
 1   car_name           15411 non-null  object
 2   brand              15411 non-null  object
 3   model              15411 non-null  object
 4   vehicle_age        15411 non-null  int64
 5   km_driven          15411 non-null  int64
 6   seller_type        15411 non-null  object
 7   fuel_type          15411 non-null  object
 8   transmission_type  15411 non-null  object
 9   mileage            15411 non-null  float64
 10  engine             15411 non-null  int64
 11  max_power          15411 non-null  float64
 12  seats              15411 non-null  int64
 13  selling_price      15411 non-null  int64
dtypes: float64(2), int64(6), object(6)
memory usage: 1.6+ MB

In [ ]:
df.isnull().sum()

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [ ]:
df=df.drop(columns=['car_name','brand','Unnamed: 0'])

In [ ]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [ ]:
len(df['model'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique()),len(df['seller_type'].unique())

(120, 5, 2, 3)

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
encoder=LabelEncoder()
df['model']=encoder.fit_transform(df['model'])

In [ ]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [ ]:
cat_features=[features for features in df.columns if df[features].dtype=='object']

In [ ]:
num_features=[features for features in df.columns if df[features].dtype!='object']

In [ ]:
num_features=[features for features in df.columns if df[features].dtype!='object' and features!='selling_price']
from sklearn.compose import ColumnTransformer
scaler=StandardScaler()
oh_transformer=OneHotEncoder(drop='first')
preprocessor=ColumnTransformer([
    ('OneHotEncoder',oh_transformer,cat_features),
    ('StandardScaler',scaler,num_features)
])

In [ ]:
y=df['selling_price']
X=df.drop(columns=['selling_price'])

In [ ]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [ ]:
X=preprocessor.fit_transform(X)

In [ ]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((10787, 14), (4624, 14), (10787,), (4624,))

In [ ]:
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [ ]:
models={
    'RandomForestRegressor':RandomForestRegressor()
,
    'DecisionTreeRegressor':DecisionTreeRegressor()
,
    'KNeighborsRegressor':KNeighborsRegressor()
,
    'LinearRegression':LinearRegression()
,
    'LogisticRegression':LogisticRegression()
}

In [ ]:
models

{'RandomForestRegressor': RandomForestRegressor(),
 'DecisionTreeRegressor': DecisionTreeRegressor(),
 'KNeighborsRegressor': KNeighborsRegressor(),
 'LinearRegression': LinearRegression(),
 'LogisticRegression': LogisticRegression()}

In [ ]:
def evaluate_model(true,predicted):
  mae=mean_absolute_error(true,predicted)
  rmse=np.sqrt(mean_squared_error(true,predicted))
  r2=r2_score(true,predicted)
  return mae,rmse,r2

In [ ]:
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(X_train,y_train)

  train_mae,train_rmse,train_r2_score=evaluate_model(y_train,model.predict(X_train))
  test_mae,test_rmse,test_r2_score=evaluate_model(y_test,model.predict(X_test))

  print(list(models.keys())[i])
  print('Model Performance for Training Set')
  print('MAE: {:.4f}'.format(train_mae))
  print('RMSE:{:.4f}'.format(train_rmse))
  print('R2 Score:{:.4f}'.format(train_r2_score))
  print('\n')
  print('Model Performance for Test Set')
  print('MAE:{:.4f}'.format(test_mae))
  print('RMSE:{:.4f}'.format(test_rmse))
  print('R2 Score:{:.4f}'.format(test_r2_score))
  print('--------------------\n')

RandomForestRegressor
Model Performance for Training Set
MAE: 39187.7846
RMSE:115103.6269
R2 Score:0.9838


Model Performance for Test Set
MAE:105667.9291
RMSE:245072.1436
R2 Score:0.9201
--------------------

DecisionTreeRegressor
Model Performance for Training Set
MAE: 4728.8897
RMSE:20329.7436
R2 Score:0.9995


Model Performance for Test Set
MAE:126920.9541
RMSE:294475.3221
R2 Score:0.8847
--------------------

KNeighborsRegressor
Model Performance for Training Set
MAE: 91830.6295
RMSE:338148.7706
R2 Score:0.8605


Model Performance for Test Set
MAE:116755.5201
RMSE:287899.8049
R2 Score:0.8898
--------------------

LinearRegression
Model Performance for Training Set
MAE: 268437.6549
RMSE:559313.7144
R2 Score:0.6183


Model Performance for Test Set
MAE:281329.9042
RMSE:507556.7988
R2 Score:0.6575
--------------------

LogisticRegression
Model Performance for Training Set
MAE: 192109.0201
RMSE:441400.8770
R2 Score:0.7623


Model Performance for Test Set
MAE:211208.9371
RMSE:479352.2858
R2 Score:0.6945
--------------------

In [ ]:
knn_params={'n_neighbors':[5,10,15,20,25,30],
            }
rf_params={'n_estimators':[100,150,200,250,300],
           'criterion':['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
           'max_depth':[1,2,3,4,5,6,7],
           'min_samples_split':[2,3,5,10,15,20]}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
random_cv=[
    ('KNN',KNeighborsRegressor(),knn_params),
    ('RandomForestRegressor',RandomForestRegressor(),rf_params)
]

In [ ]:
random_cv

[('KNN', KNeighborsRegressor(), {'n_neighbors': [5, 10, 15, 20, 25, 30]}),
 ('RandomForestRegressor',
  RandomForestRegressor(),
  {'n_estimators': [100, 150, 200, 250, 300],
   'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
   'max_depth': [1, 2, 3, 4, 5, 6, 7],
   'min_samples_split': [2, 3, 5, 10, 15, 20]})]

In [ ]:
best_params={}
for name,model,param in random_cv:
  random=RandomizedSearchCV(model,param,n_iter=10,cv=3,verbose=2,n_jobs=-1)
  random.fit(X_train,y_train)
  best_params[name]=random.best_params_
for model in best_params:
  print(model,best_params[model])
  print('----------------------------------------')

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 10 candidates, totalling 30 fits
KNN {'n_neighbors': 5}
----------------------------------------
RandomForestRegressor {'n_estimators': 150, 'min_samples_split': 15, 'max_depth': 6, 'criterion': 'friedman_mse'}
----------------------------------------

In [ ]:
models={
    'RandomForestRegressor':RandomForestRegressor(n_estimators=150, min_samples_split=15, max_depth=6, criterion='friedman_mse')
,
    'KNeighborsRegressor':KNeighborsRegressor(n_neighbors= 5)}

In [ ]:
for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(X_train,y_train)

  train_mae,train_rmse,train_r2_score=evaluate_model(y_train,model.predict(X_train))
  test_mae,test_rmse,test_r2_score=evaluate_model(y_test,model.predict(X_test))

  print(list(models.keys())[i])
  print('Model Performance for Training Set')
  print('MAE: {:.4f}'.format(train_mae))
  print('RMSE:{:.4f}'.format(train_rmse))
  print('R2 Score:{:.4f}'.format(train_r2_score))
  print('\n')
  print('Model Performance for Test Set')
  print('MAE:{:.4f}'.format(test_mae))
  print('RMSE:{:.4f}'.format(test_rmse))
  print('R2 Score:{:.4f}'.format(test_r2_score))
  print('--------------------\n')

RandomForestRegressor
Model Performance for Training Set
MAE: 127151.1269
RMSE:275108.9777
R2 Score:0.9077


Model Performance for Test Set
MAE:142259.6116
RMSE:303215.7067
R2 Score:0.8777
--------------------

KNeighborsRegressor
Model Performance for Training Set
MAE: 91830.6295
RMSE:338148.7706
R2 Score:0.8605


Model Performance for Test Set
MAE:116755.5201
RMSE:287899.8049
R2 Score:0.8898
--------------------